# Created using wingetcreate 1.6.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Microsoft.Azcopy
PackageVersion: 10.26.0
PackageLocale: en-US
Publisher: Azcopy
PackageName: Azcopy
License: Azcopy License
ShortDescription: A command-line utility that is used to copy data to and from containers and file shares in Azure Storage accounts
ManifestType: defaultLocale
ManifestVersion: 1.6.0
